WEB_DIRECTORY = "./js"

from .nodes.IndexMultiple import NODE_CLASS_MAPPINGS as INDEX_MAPPINGS
from .nodes.IndexMultiple import NODE_DISPLAY_NAME_MAPPINGS as INDEX_DISPLAY

from .nodes.CLIPEncodeMultiple import NODE_CLASS_MAPPINGS as CLIP_MAPPINGS
from .nodes.CLIPEncodeMultiple import NODE_DISPLAY_NAME_MAPPINGS as CLIP_DISPLAY

from .nodes.AKSamplerSettings import NODE_CLASS_MAPPINGS as AKS_MAPPINGS
from .nodes.AKSamplerSettings import NODE_DISPLAY_NAME_MAPPINGS as AKS_DISPLAY

from .nodes.AKSettingsOut import NODE_CLASS_MAPPINGS as AKOUT_MAPPINGS
from .nodes.AKSettingsOut import NODE_DISPLAY_NAME_MAPPINGS as AKOUT_DISPLAY

from .nodes.IsOneOfGroupsActive import NODE_CLASS_MAPPINGS as GROUPCHK_MAPPINGS
from .nodes.IsOneOfGroupsActive import NODE_DISPLAY_NAME_MAPPINGS as GROUPCHK_DISPLAY

from .nodes.RepeatGroupState import NODE_CLASS_MAPPINGS as RPSTATE_MAPPINGS
from .nodes.RepeatGroupState import NODE_DISPLAY_NAME_MAPPINGS as RPSTATE_DISPLAY

from .nodes.PreviewRawText import NODE_CLASS_MAPPINGS as PRTSTATE_MAPPINGS
from .nodes.PreviewRawText import NODE_DISPLAY_NAME_MAPPINGS as PRTSTATE_DISPLAY

from .nodes.CLIPTextEncodeCached import NODE_CLASS_MAPPINGS as CLCSTATE_MAPPINGS
from .nodes.CLIPTextEncodeCached import NODE_DISPLAY_NAME_MAPPINGS as CLCSTATE_DISPLAY

from .nodes.AKBase import NODE_CLASS_MAPPINGS as AKBSTATE_MAPPINGS
from .nodes.AKBase import NODE_DISPLAY_NAME_MAPPINGS as AKBSTATE_DISPLAY

from .nodes.AKBaseSettings import NODE_CLASS_MAPPINGS as AKBSSTATE_MAPPINGS
from .nodes.AKBaseSettings import NODE_DISPLAY_NAME_MAPPINGS as AKBSSTATE_DISPLAY

from .nodes.AKBaseSettingsOut import NODE_CLASS_MAPPINGS as AKBOSTATE_MAPPINGS
from .nodes.AKBaseSettingsOut import NODE_DISPLAY_NAME_MAPPINGS as AKBOSTATE_DISPLAY

NODE_CLASS_MAPPINGS = {
    **INDEX_MAPPINGS,
    **CLIP_MAPPINGS,
    **AKS_MAPPINGS,
    **AKOUT_MAPPINGS,
    **GROUPCHK_MAPPINGS,
    **RPSTATE_MAPPINGS,
    **PRTSTATE_MAPPINGS,
    **CLCSTATE_MAPPINGS,
    **AKBSTATE_MAPPINGS,
    **AKBSSTATE_MAPPINGS,
    **AKBOSTATE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **INDEX_DISPLAY,
    **CLIP_DISPLAY,
    **AKS_DISPLAY,
    **AKOUT_DISPLAY,
    **GROUPCHK_DISPLAY,
    **RPSTATE_DISPLAY,
    **PRTSTATE_DISPLAY,
    **CLCSTATE_DISPLAY,
    **AKBSTATE_DISPLAY,
    **AKBSSTATE_DISPLAY,
    **AKBOSTATE_DISPLAY,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
